### ISSUE TITLE
How start a java process with debug enabled?

### ISSUE THREAD

**Issue by LinArcX** [dansomething/coc-java-debug#1]
Hi. first of all, let me thank you for this plugin. I tired to debug a super simple java application that contains only one file: __main.java__:
```
public class main {
    public static void main(String[] args) {
        System.out.println("foo");
        System.out.println("bar");
    }
}
```
So, i don't use maven or other fancy stuff. Seems in __README__ we need maven to start a java process. Is it necessary?

> First, run a Java process with debug enabled. Make sure its configured to pause and wait for a remote debugger on port 5005.
> For example:
> mvn test -Dmaven.surefire.debug

**Comment by dansomething** [comment]
Maven is not required. That is just an example using it. As long as you enable the remote debugger of a Java process you should be able to connect to it.  For your example of a single java file named "main", it should work like this to start the java process with the debug server enabled on port 5005.

    javac main.java
    java -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=5005,suspend=y main

A quick search on Google for "java remote debugging" should reveal a lot of other examples.

**Comment by LinArcX** [comment]
Yeah, it works. Thank you.

**Comment by dansomething** [comment]
I added this plain Java example to the readme.
