### ISSUE TITLE
Vimspector doesnt stop at breakpoints

### ISSUE THREAD

**Issue by binarydigitz01** [dansomething/coc-java-debug#10]
I followed the exact steps on readme.md. I put some breakpoints and then when i connect to the remote host it just runs the code without stopping.
here is my .vimspector.json:
`
{
  "adapters": {
    "java-debug-server": {
      "name": "vscode-java",
      "port": "${AdapterPort}"
    }
  },
  "configurations": {
    "Java Attach": {
      "default": true,
      "adapter": "java-debug-server",
      "configuration": {
        "request": "attach",
        "host": "127.0.0.1",
        "port": "5005"
      },
      "breakpoints": {
        "exception": {
          "caught": "N",
          "uncaught": "N"
        }
      }
    }
  }
}

`
EDIT: I got it to work on maven project, But still cant cofigure it on a stand alone file.

**Comment by binarydigitz01** [comment]
I finally got it to work by putting "stopAtEntry":true. Here is my updated .vimspector.json:
{
    "adapters": {
        "java-debug-server": {
            "name": "vscode-java",
            "port": "${AdapterPort}"
        }
    },
    "configurations": {
        "Java Attach": {
            "default": true,
            "adapter": "java-debug-server",
            "configuration": {
                "request": "attach",
                "host": "127.0.0.1",
                "port": "5005",
                "stopAtEntry": true
            },
            "breakpoints": {
                "exception": {
                    "caught": "N",
                    "uncaught": "N"
                }
            }
        }
    }
}

**Comment by dansomething** [comment]
That is strange. I'd expect it to stop at any breakpoint you set before running the debugger. If not, it is possibly a bug in Vimspector since this plugin only connects Vimspector to the running debug server in jdt.ls. Glad you found a workaround solution using `"stopAtEntry": true`.
