### ISSUE TITLE
Did the .vimspector json schema change?

### ISSUE THREAD

**Issue by milind-shakya-sp** [dansomething/coc-java-debug#11]
Getting the following error

```The specified adapter 'java-debug-server' is not available. Did you forget to run 'install_gadget.py'?```

My configuration is
```
{
  "adapters": {
    "java-debug-server": {
      "name": "vscode-java",
      "port": "${AdapterPort}"
    }
  },
  "configurations": {
    "Java Attach": {
      "adapter": "java-debug-server",
      "configuration": {
        "request": "attach",
        "host": "localhost",
        "port": "29220"
      },
      "breakpoints": {
        "exception": {
          "caught": "N",
          "uncaught": "N"
        }
      }
    }
  }
}```

**Comment by dansomething** [comment]
It appears that something has changed in Vimspector. According to the [docs](https://github.com/puremourning/vimspector#manual-gadget-installation) it should still be possible to set `adapters` in the `.vimspector.json` file.

>You can then configure the adapter manually in the adapters section of your .vimspector.json or in a gadgets.json.

Can you try setting the adapters config in the [Vimspector gadgets.json](https://github.com/puremourning/vimspector#the-gadget-directory) file as a workaround?

**Comment by milind-shakya-sp** [comment]
Did a quick test by adding the following to the `.gadgets.json` file. But did not help. Not sure if there any other configuration that coc-java-debug needs to follow?

```
"java-debug-server": {
      "name": "vscode-java",
      "port": "${AdapterPort}"
    }
```

**Comment by dansomething** [comment]
I would expect `.gadgets.json` to have the full `adapters` config just as it is in `.vimspector.json`.

```json
{
  "adapters": {
    "java-debug-server": {
      "name": "vscode-java",
      "port": "${AdapterPort}"
    }
  }
}
```

**Comment by opensourcegeek** [comment]
I was hitting the same issue after upgrading plugins but the workaround suggested by @dansomething seems to be working.

**Comment by milind-shakya-sp** [comment]
Looks like I was updating the wrong `.gadgets.json` file. I had to create a new `.gadgets.json` file in the project root to get it working.

Thanks
