### ISSUE TITLE
Failed to attach to remote debugee VM

### ISSUE THREAD

**Issue by fedoranvar** [dansomething/coc-java-debug#12]
Good day to you!

After `:CocCommand java.debug.vimspector.start` received `connection refused`:

![image](https://user-images.githubusercontent.com/52028706/99940584-415aae80-2d8e-11eb-987a-9808f939c5b8.png)

.gadgets.json:
![image](https://user-images.githubusercontent.com/52028706/99940672-7961f180-2d8e-11eb-99d9-758d40642de5.png)

.vimspector.json:
![image](https://user-images.githubusercontent.com/52028706/99940687-81219600-2d8e-11eb-969f-c2e90eedfabd.png)

`netstat -lnpt`:
![image](https://user-images.githubusercontent.com/52028706/99940843-d067c680-2d8e-11eb-87cf-f0aa0dc62f8a.png)

Any help would be great!

Thanks!

**Comment by dansomething** [comment]
`Failed to attach to remote debuggee VM.` is a message I'd expect to see if there is no JVM process waiting for a debugger to attach to on the specific port under `configurations`. It looks like you have the attach port set to 9000.

In your netstat output I don't see any Java process on port 9000. Did you start a Java process with the debug flags set? Here's a [simplified example](https://github.com/dansomething/coc-java-debug#start-the-debug-session) from the readme. The example uses port 5005, but you can change it to 9000 to match your config.

**Comment by fedoranvar** [comment]
@dansomething,  you're right!

Indeed, recently for some reasons i've changed port 9000 to 9001 - now it's all working,

Good day to you!

**Comment by nilm987521** [comment]
the same issue "[Failed to attach to remote debugee VM #12](https://github.com/dansomething/coc-java-debug/issues/12)"
but I didn't change port 5005....How can I fix it?

**Comment by dansomething** [comment]
@nilm987521 have you confirmed the Java process you want to debug is waiting for a connection on port 5005? Did you set the port to 5005 in your `.vimspector.json` file?

**Comment by nilm987521** [comment]
@dansomething 
this is my ```.vimspector.json``` under project folder,

```{
  "adapters": {
    "java-debug-server": {
      "name": "vscode-java",
      "port": "${AdapterPort}"
    }
  },
  "configurations": {
    "Java Attach": {
      "default": true,
      "adapter": "java-debug-server",
      "configuration": {
        "request": "attach",
        "host": "127.0.0.1",
        "port": "5005"
      },
      "breakpoints": {
        "exception": {
          "caught": "N",
          "uncaught": "N"
        }
      }
    }
  }
}
```

**Comment by dansomething** [comment]
What about the Java process? Is it waiting for a connection on port 5005? Also, are you running the latest versions of coc-java and eclipse.jdt.ls?

Without more information, it will be difficult to troubleshoot the issue. Providing the following may help:
**Versions of relevant software**
 - vim:
 - coc.nvim:
 - coc-java:
 - vimspector:
 - java:
 - maven:

**Relevant logs and error messages**
* View the trace logging output for the Java language server:
    * Set `{ "java.trace.server": "verbose" }` in `:CocSettings`.
    * Run the command `:CocCommand workspace.showOutput java`.
    * Are there any errors?
* View the Vimspector log `:VimspectorShowOutput Vimspector`.
    * Are the any errors?
* After running the command `:CocCommand java.debug.vimspector.start` Do you see a message like `[coc.nvim] Java debug server started on port` in the output of `:messages`?
