### ISSUE TITLE
Multiple Vimspector debugging sessions at the same time?

### ISSUE THREAD

**Issue by Frederick888** [dansomething/coc-java-debug#16]
I'm using coc-java-debug under NeoVim 0.4.4.

Now I'd like to debug a few applications at the same time since they communicate with each other via API requests and/or queues. However it seems at the moment if I launch a new debugging session via `CocCommand java.debug.vimspector.start`, it replaces the existing one instead of starting a new one.

Is it possible to have multiple debugging sessions at the same time?

**Comment by dansomething** [comment]
To my knowledge Vimspector doesn't support multiple simultaenous debug sessions. I think you'd have to open multiple instances of Vim+Vimspector to make it work.
