### ISSUE TITLE
Is hot-swap code possible?

### ISSUE THREAD

**Issue by nbfhscl** [dansomething/coc-java-debug#31]
Is hot-swap code possible?

**Comment by nbfhscl** [comment]
found this in vimspector:

> Hot code replace
When using the java debug server, Vimspector supports the hot code replace custom feature. By default, when the underlying class files change, vimspector asks the user if they wish to reload these classes at runtime.
This behaviour can be customised:
let g:ycm_java_hotcodereplace_mode = 'ask' - the default, ask the user for each reload.
let g:ycm_java_hotcodereplace_mode = 'always' - don't ask, always reload
let g:ycm_java_hotcodereplace_mode = 'never' - don't ask, never reload

**Comment by dansomething** [comment]
Related threads and docs:
#9
puremourning/vimspector#252
https://github.com/puremourning/vimspector#hot-code-replace
