### ISSUE TITLE
Static variables not visible in Vimspector

### ISSUE THREAD

**Issue by gagara** [dansomething/coc-java-debug#44]
**Describe the issue**
Static variables are not shown in "Variables" view in vimspector.
In `vscode-java-debug` plugin there is an config option
>java.debug.settings.showStaticVariables: show static variables in "Variables" viewlet, defaults to false.

I wonder if something needs to be enabled/configured in this plugin or it is not supported.

**To Reproduce**
1. Launch debug against code which contains static vairables
3. No static variables in "Variables" view

**Expected behavior**
Static variables should be visible

**Versions of relevant software**
 - vim: `9.1.445`
 - coc.nvim: `392264f475`
 - coc-java: `1.15.2`
 - vimspector: latest `master`
 - java: 21
 - maven: -

**Comment by dansamsara** [comment]
Sorry, normally I'm more responsive, but I've been extra busy and traveling. I see you've discovered this feature wasn't implemented. I'll take a look at your PR as soon as I can.

**Comment by dansomething** [comment]
PR merged. This will be fixed in the next release.
